# Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [21]:
import numpy as np
import random
num = np.random.randint(0, 100, (10, 10))

print(num)

[[55 94  6 54  2 95 94 12 49 88]
 [30 79 27 42 71 18 37 53 17  2]
 [75 14 31 40 57 77 27 99 97 50]
 [ 2 85 21 51 21 32 60  2 19 67]
 [14 85 44 75 70 59 55 44 78 82]
 [10 50  3 18 38 75  7  2  8 61]
 [33 80 13 29 80 61 29 28 42 36]
 [10 13 47 37 61 78 64 19 91 27]
 [99 85 17 23 11 14 27 81 83 77]
 [25 41 18 89 12 43 16  0 98 51]]
